development:
  adapter: postgresql
  encoding: unicode
  database: nlpt_dev
  pool: 5
  username: erichagemann
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: nlpt_test
  pool: 5
  username: erichagemann
  password:

